#26 Progress- to a new error! RuntimeError: found top level layout element header...
RuntimeError: Found top level layout element "Header" inside element "Column". Top level layout elements can not be nested but must be direct children of the page content.

Attempting to correct:
Changing from contextmanager to async context manager.
Adding in appropriate async/await parts in main and theme.py