#26 Fix Deployment
Issue changed to:

Traceback (most recent call last):
  File "main.py", line 67, in <module>
  File "configparser.py", line 941, in __getitem__
KeyError: 'Preferences'